---
- name: print kubeconfig for eks clusters
  hosts: localhost
  tasks:
    - name: get cluster list
      command: "aws eks list-clusters"
      register: listclust

    - name: set clusters list
      set_fact:
        clusters: "{{ (listclust.stdout | from_json).clusters }}"

    - name: get deets
      command: "aws eks describe-cluster --name {{ item }}"
      register: clusterdetail
      loop: "{{ clusters }}"

    - name: create kubectl config for eks masters
      template:
        src: kubeconfig.yaml.j2
        dest: "/root/out/kubectl.eksclusters.{{ (item.stdout | from_json).cluster.name }}.generated.yaml"
      loop: "{{ clusterdetail.results }}"
